name: Docker Hub Build

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine Docker Hub org and tag from git branch
        run: |
          if [[ "$GITHUB_REF_NAME" =~ release/(.*) ]]; then
              echo DOCKERHUB_ORG="usdotfhwastolcandidate" >> $GITHUB_ENV
              echo DOCKERHUB_TAG="${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
              echo DOCKERHUB_ORG="usdotfhwastoldev" >> $GITHUB_ENV
              # Replace / with - in branch name
              echo DOCKERHUB_TAG=${GITHUB_REF_NAME/\//-} >> $GITHUB_ENV
          fi
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKERHUB_ORG }}/${{ github.event.repository.name }}:${{ env.DOCKERHUB_TAG }}